name: First Workflow

on:
  push: 
    branches: 
      - main 

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: print a welcome message
        run:  echo "welcome to our first Github Actions workflow"
      - name: print the date
        run: date
      - name: checkout repository
        uses: actions/checkout@v6.0.2
      - name: list repository files
        run: ls -la
